### ISSUE TITLE
Add image

### ISSUE THREAD

**Issue by shehzadi** [iovisor/hoverui#6]
<img width="1085" alt="screen shot 2016-03-17 at 5 31 08 pm" src="https://cloud.githubusercontent.com/assets/1617259/13865241/8158d700-ec66-11e5-829c-2bcc02cdec05.png">

**Comment by maxbielenberg** [comment]
![output_pny0iq](https://cloud.githubusercontent.com/assets/15094187/19744811/ee431d0e-9b83-11e6-9f70-126c0f4fb50c.gif)
